name: Lint

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          yarn

  Lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          yarn lint
        env:
          CI: true
    needs: setup

  Test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          yarn test
    needs: setup
